filetype plugin on
filetype indent on
syntax on

set linebreak
set mouse=a
set viminfo='10,<100,:100,%,n~/.vim/.viminfo
set incsearch
set hlsearch

let Tlist_Compact_Format = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Close_On_Select = 1
nnoremap <C-l> :TlistToggle<CR>
