modkey = Mod4

bar_action = /home/igor/.scripts/batn.sh
bar_font = -xos4-terminus-medium-*-*-*-12-*-*-*-*-*-*-*
bar_at_bottom = 1
bar_enabled = 0

program[xterm] = st -e tmux
bind[xterm] = Mod4+Return

program[stw] = stw -e tmux
bind[stw] = Mod4+Shift+Return

program[work] = work 1200
bind[work] = MOD+c

program[rest] = rest 300
bind[rest] = MOD+m

bind[iconify] = MOD+v
bind[uniconify] = MOD+Shift+v

program[screenshot_all] = screenshot.sh full
bind[screenshot_all] = MOD+a
program[screenshot_wind] = screenshot.sh window
bind[screenshot_wind] = MOD+Shift+a

bind[] = MOD+Shift+Delete
bind[] = MOD+w
bind[] = MOD+Shift+w
