set-option -g prefix C-a
bind-key C-a send-prefix
setw -g mode-keys vi
bind r source-file ~/.tmux.conf \; display "Reloaded!"
setw -g mode-keys vi 
unbind-key j
bind-key j select-pane -D 
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

bind-key Enter split-window -h
bind-key / split-window
unbind-key C-o
unbind-key M-o
bind-key C-u rotate-window -D\; select-pane -D
bind-key C-y rotate-window -U\; select-pane -U

bind-key C-j resize-pane -D 5
bind-key C-k resize-pane -U 5
bind-key C-h resize-pane -L 5
bind-key C-l resize-pane -R 5
